GET http://127.0.0.1:3000/api/products

###
POST http://127.0.0.1:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZW1haWwuY29tIiwiaWF0IjoxNjg0MDgzMjMxfQ.drc0sftAN_ixSzFuRIJkRQJBJPtZ3ZbXmoSekzMqAVU

{
    "name": "lexury product 2",
    "unitPrice": 16,
    "stock": 4,
    "description": "This is product 10",
    "images": "[\"https://example.com/product10/image1.jpg\", \"https://example.com/product10/image2.jpg\"]",
    "catagory": "type 1"
}

### another user
POST http://127.0.0.1:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNvbWVvbmVAZW1haWwuY29tIiwiaWF0IjoxNjg0MDgzMjU4fQ.kI5WJyBSSZuXIBZgqn7z7UjsHoEzMN7jKKJDCLP90gM

{
    "name": "lexury product 9n",
    "unitPrice": 16,
    "stock": 4,
    "description": "This is product 10",
    "images": "[\"https://example.com/product10/image1.jpg\", \"https://example.com/product10/image2.jpg\"]",
    "catagory": "type 1n"
}
### update by valid user
PUT http://127.0.0.1:3000/api/products/64611549973e352b03215362
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZW1haWwuY29tIiwiaWF0IjoxNjg0MDgzMjMxfQ.drc0sftAN_ixSzFuRIJkRQJBJPtZ3ZbXmoSekzMqAVU

{
    "name": "lexury product bb",
    "unitPrice": 16,
    "stock": 4,
    "description": "This is product 10",
    "images": "[\"https://example.com/product10/image1.jpg\", \"https://example.com/product10/image2.jpg\"]",
    "catagory": "type 1bb"
}


### update by invalid user
PUT http://127.0.0.1:3000/api/products/64611549973e352b03215362
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNvbWVvbmVAZW1haWwuY29tIiwiaWF0IjoxNjg0MDgzMjU4fQ.kI5WJyBSSZuXIBZgqn7z7UjsHoEzMN7jKKJDCLP90gM

{
    "name": "lexury product bb",
    "unitPrice": 16,
    "stock": 4,
    "description": "This is product 10",
    "images": "[\"https://example.com/product10/image1.jpg\", \"https://example.com/product10/image2.jpg\"]",
    "catagory": "type 1bb"
}



### 
DELETE  http://127.0.0.1:3000/api/products/646118e032262892a4da6840
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZW1haWwuY29tIiwiaWF0IjoxNjg0MDgzMjMxfQ.drc0sftAN_ixSzFuRIJkRQJBJPtZ3ZbXmoSekzMqAVU

{
    "name": "lexury product 98",
    "unitPrice": 16,
    "stock": 4,
    "description": "This is product 10",
    "images": "[\"https://example.com/product10/image1.jpg\", \"https://example.com/product10/image2.jpg\"]",
    "catagory": "type 1"
}


