POST http://127.0.0.1:3000/api/users
Content-Type: application/json

{
   "name":"John wick",
   "email":"email@email.com",
   "password": "strongpassword"
}

###
POST http://127.0.0.1:3000/api/users/login
Content-Type: application/json

{
   "email":"email@email.com",
   "password": "strongpassword"
}

###
POST http://127.0.0.1:3000/api/users
Content-Type: application/json

{
   "name":"Some One",
   "email":"someonddafdae44ee@email.com",
   "password": "somepassword"
}

###
GET http://127.0.0.1:3000/api/users/6460fc09b9abd3cfefeab010




###
