POST http://127.0.0.1:3000/api/users
Content-Type: application/json

{
   "name":"some person",
   "email":"otheremail24@email.com",
   "password":"superstrongpassword"
}

###
GET http://127.0.0.1:3000/api/users/64620edb9af0c6aa7d2ef3b2



###
